%%{init: {'themeVariables': { 'fontSize': '20px', 'nodeSpacing': 70, 'rankSpacing': 100 }}}%%
flowchart LR

%% OT Network
subgraph OT["OT Network"]
    DGIC["DGIC"]
end

%% Visual Firewall (using a dummy node with a tall label)
FIREWALL["|||<br>|||<br>|||<br>Firewall<br>|||<br>|||<br>|||"]

%% IT Network
subgraph IT["IT Network"]
    TLG["Telegraf"]
    RMQ["RabbitMQ"]
    CONS["Python Consumer"]
    DB["Local InfluxDB"]
end

%% Flow connections
DGIC -- data logs over UDP --> FIREWALL --> TLG --> DB
TLG -->|MQTT| RMQ --> CONS